[package]
name = "invadors"
version = "0.1.0"
edition = "2021"
authors = ["Sami Gabor"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17.5"
rusty_audio = "1.2"
rusty_time = "0.12"
